### ISSUE TITLE
Pickle file for LAEO AVA validation 

### ISSUE THREAD

**Issue by fei-chang** [AVAuco/laeonetplus#4]
Hello, 

Thanks for providing this amazing repo on LAEO task!

I’m currently working on a project and hoping to use the AVA LAEO dataset. It will be a great help for me if the head box annotations could be made available. Therefore, if possible, would you mind releasing a link to download the validation pickle file ‘AVA_LAEO_all_rounds1-2-3_val__v2.2_tracks.pkl’ as you did with the train?

Thanks a lot!

**Comment by mjmarin** [comment]
Dear @fei-chang ,
thank you for your interest in our project.

Sure, you can download the corresponding file from [here](https://ucordoba-my.sharepoint.com/:u:/g/personal/in1majim_uco_es/Ed41BMHX43VJqL5OcnGubtEB5LEUEvRrvLMeLiH_GP-gIA?e=wrliGh).
Regards.
